export const actionTypes = {
  GET_DATA_START: "GET_DATA_START",
  GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
  GET_DATA_ERROR: "GET_DATA_ERROR",
  TOGGLE_CHECKOUT_MODAL: "TOGGLE_CHECKOUT_MODAL",
  TOGGLE_CHECKOUT_MODAL_CLOSE: "TOGGLE_CHECKOUT_MODAL_CLOSE",
  PLACE_ORDER: "PLACE_ORDER",
  CHECK_OUT: "CHECK_OUT",
};
